AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  BucketNameSrc:
    Type: String
  BucketNameDest:
    Type: String

Resources:
  Task2S3Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameSrc
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  Task2BucketPolicy1:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Task2S3Bucket1
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Deny
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref Task2S3Bucket1
                - /*
            Principal: '*'

  Task2S3Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameDest
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  Task2BucketPolicy2:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Task2S3Bucket2
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - 's3:PutObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref Task2S3Bucket2
                - /*
            Principal: '*'

  Task2CopyLambdaRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: 
                  - !Sub 'arn:aws:s3:::${Task2S3Bucket1}/*'
                  - !Sub 'arn:aws:s3:::${Task2S3Bucket2}/*'

  Task2CopyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'copy-file-lambda-${AWS::StackName}-${AWS::Region}'
      Handler: index.handler
      Role: !GetAtt Task2CopyLambdaRole.Arn
      Runtime: python3.12
      Environment:
        Variables:
          SRC_BUCKET_NAME: !Ref Task2S3Bucket1
          DEST_BUCKET_NAME: !Ref Task2S3Bucket2
          FILE_NAME: "wrong-index.txt"
      Code:
        ZipFile: |
          import json
          import boto3
          import os
          import time

          s3 = boto3.client('s3')

          def handler(event, context):
              time.sleep(4)
              source_bucket = os.getenv("SRC_BUCKET_NAME")
              source_key = os.getenv("FILE_NAME")
              destination_bucket = os.getenv("DEST_BUCKET_NAME")
              new_key = 'copied-' + source_key

              # Copy the object to the destination bucket with a new name
              copy_source = {'Bucket': source_bucket, 'Key': source_key}
              s3.copy_object(CopySource=copy_source, Bucket=destination_bucket, Key=new_key)
              
              return {
                  'statusCode': 200,
                  'body': json.dumps('File copied successfully!')
              }

  S3PutObjectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Task2CopyLambdaFunction.Arn
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt Task2S3Bucket2.Arn

  S3GetObjectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Task2CopyLambdaFunction.Arn
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt Task2S3Bucket1.Arn

Outputs:
  S3Bucket1Name:
    Description: "Source S3 Bucket Name"
    Value: !Ref Task2S3Bucket1

  S3Bucket2Name:
    Description: "Destination S3 Bucket Name"
    Value: !Ref Task2S3Bucket2

  LambdaFunctionName:
    Description: "Lambda Function Name"
    Value: !Ref Task2CopyLambdaFunction
